import streamlit as st
import pandas as pd
import numpy as np
import requests
from beautifulsoup4 import BeautifulSoup, Comment
from io import StringIO
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error

# 🎯 Convertire minute MM:SS → float
def convert_minutes(mp):
    try:
        m, s = map(int, mp.split(":"))
        return round(m + s/60, 2)
    except:
        return np.nan

# 🧠 Predicție + RMSE pentru fiecare coloană
def predict_next_game(df):
    if len(df) < 3:
        return {c: "Insuficiente date" for c in df.columns}, None
    X = np.arange(len(df)).reshape(-1, 1)
    preds = {}
    rmses = {}
    for c in df.columns:
        model = RandomForestRegressor(random_state=0)
        model.fit(X, df[c])
        y_pred = model.predict(X)
        rmse = np.sqrt(mean_squared_error(df[c], y_pred))
        prediction = model.predict([[len(df)]])[0]
        preds[c] = f"{prediction:.1f}"
        rmses[c] = f"{rmse:.2f}"
    return preds, rmses

# 📊 Scrape date din BBR (inclusiv comentarii pentru NBA)
def scrape_stats(url, league, debug=False):
    headers = {'User-Agent': 'Mozilla/5.0'}
    r = requests.get(url, headers=headers)
    soup = BeautifulSoup(r.text, 'html.parser')
    
    table_id = "wnba_pgl_basic" if league == "wnba" else "player_game_log_reg"
    
    if league == "nba":
        comments = soup.find_all(string=lambda text: isinstance(text, Comment))
        for c in comments:
            if table_id in c:
                soup = BeautifulSoup(c, "html.parser")
                break

    tbl = soup.find("table", {"id": table_id})
    
    if debug:
        st.write(f"🔍 URL folosit: {url}")
        st.write(f"⚠️ Tabelul {'găsit ✅' if tbl else 'NU a fost găsit ❌'}")
        st.code(tbl.prettify()[:1000] if tbl else "Tabel inexistent", language="html")

    if not tbl:
        return pd.DataFrame()

    df = pd.read_html(StringIO(str(tbl)))[0]
    df = df[df["Rk"] != "Rk"].reset_index(drop=True)
    df["MIN"] = df["MP"].astype(str).apply(convert_minutes)

    for col in ["PTS", "TRB", "AST", "PF"]:
        df[col] = pd.to_numeric(df[col], errors="coerce")

    return df[["MIN", "PTS", "TRB", "AST", "PF"]].dropna()

# 🔗 Generează URL-ul corect
def generate_url(pid, league, season):
    if league == "wnba":
        return f"https://www.basketball-reference.com/wnba/players/{pid[0]}/{pid}/gamelog/{season}/"
    else:
        return f"https://www.basketball-reference.com/players/{pid[0]}/{pid}/gamelog/{season}/"

# 🧑‍💼 Jucători NBA / WNBA (extinde după nevoie)
nba_players = {
  "Precious Achiuwa": "achiupr01",
  "Steven Adams": "adamsst01",
  "Bam Adebayo": "adebaba01",
  "Ochai Agbaji": "agbajoc01",
  "Santi Aldama": "aldamsa01",
  "Trey Alexander": "alexatr01",
  "Ty-Shon Alexander": "alexaty01",
  "Nickeil Alexander-Walker": "alexani01",
  "Rawle Alkins": "alkinra01",
  "Grayson Allen": "allengr01",
  "Jarrett Allen": "allenja01",
  "Timmy Allen": "allenti01",
  "Jose Alvarado": "alvarjo01",
  "Justin Anderson": "anderju01",
  "Kyle Anderson": "anderky01",
  "Giannis Antetokounmpo": "antetgi01",
  "Kostas Antetokounmpo": "antetko01",
  "Thanasis Antetokounmpo": "antetth01",
  "Cole Anthony": "anthoco01",
  "OG Anunoby": "anunoog01",
  "Ryan Arcidiacono": "arcidry01",
  "Deni Avdija": "avdijde01",
  "Joel Ayayi": "ayayijo01",
  "Deandre Ayton": "aytonde01",
  "Udoka Azubuike": "azubuud01",
  "Ibou Badji": "badjiib01",
  "Marcus Bagley": "baglema02",
  "Marvin Bagley III": "baglema01",
  "Amari Bailey": "baileam01",
  "Patrick Baldwin Jr.": "baldwpa01",
  "LaMelo Ball": "ballla01",
  "Lonzo Ball": "balllo01",
  "Mo Bamba": "bambamo01",
  "Paolo Banchero": "banchpa01",
  "Desmond Bane": "banede01",
  "Dalano Banton": "bantoda01",
  "Cat Barber": "barbeca01",
  "Dominick Barlow": "barlodo01",
  "Harrison Barnes": "barneha02",
  "Scottie Barnes": "barnesc01",
  "RJ Barrett": "barrerj01",
  "Paris Bass": "basspa01",
  "Charles Bassey": "bassech01",
  "Emoni Bates": "batesem01",
  "Keita Bates-Diop": "bateske01",
  "Jamison Battle": "battlja01",
  "Nicolas Batum": "batumni01",
  "Damion Baugh": "baughda01",
  "Kent Bazemore": "bazemke01",
  "Darius Bazley": "bazleda01",
  "Bradley Beal": "bealbr01",
  "Malik Beasley": "beaslma01",
  "MarJon Beauchamp": "beaucma01",
  "Reece Beekman": "beekmre01",
  "Jordan Bell": "belljo01",
  "DeAndre' Bembry": "bembrde01",
  "Jules Bernard": "bernaju01",
  "Dāvis Bertāns": "bertada01",
  "Patrick Beverley": "beverpa01",
  "Saddiq Bey": "beysa01",
  "Tyler Bey": "beyty01",
  "Khem Birch": "birchkh01",
  "Goga Bitadze": "bitadgo01",
  "Onuralp Bitim": "bitimon01",
  "Bismack Biyombo": "biyombi01",
  "Anthony Black": "blackan01",
  "Leaky Black": "blackle01",
  "Buddy Boeheim": "boehebu01",
  "Bogdan Bogdanović": "bogdabo01",
  "Bojan Bogdanović": "bogdabo02",
  "Bol Bol": "bolbo01",
  "Marques Bolden": "boldema01",
  "Leandro Bolmaro": "bolmale01",
  "Adem Bona": "bonaad01",
  "Jordan Bone": "bonejo01",
  "Devin Booker": "bookede01",
  "Brandon Boston Jr.": "bostobr01",
  "Chris Boucher": "bouchch01",
  "James Bouknight": "bouknja01",
  "Jamaree Bouyea": "bouyeja01",
  "Ky Bowman": "bowmaky01",
  "Tony Bradley": "bradlto01",
  "Malaki Branham": "branhma01",
  "Jarrell Brantley": "brantja01",
  "Christian Braun": "braunch01",
  "Ignas Brazdeikis": "brazdig01",
  "Jalen Bridges": "bridgja01",
  "Mikal Bridges": "bridgmi01",
  "Miles Bridges": "bridgmi02",
  "Amida Brimah": "brimaam01",
  "Oshae Brissett": "brissos01",
  "Izaiah Brockington": "brockiz01",
  "Malcolm Brogdon": "brogdma01",
  "Armoni Brooks": "brookar01",
  "Dillon Brooks": "brookdi01",
  "Keion Brooks Jr.": "brookke02",
  "Bruce Brown": "brownbr01",
  "Charlie Brown Jr.": "brownch02",
  "Chaundee Brown Jr.": "brownch05",
  "Greg Brown III": "browngr01",
  "Jaylen Brown": "brownja02",
  "Kendall Brown": "brownke03",
  "Kobe Brown": "brownko01",
  "Moses Brown": "brownmo01",
  "Sterling Brown": "brownst02",
  "Troy Brown Jr.": "browntr01",
  "Jalen Brunson": "brunsja01",
  "Thomas Bryant": "bryanth01",
  "Shaq Buchanan": "buchash01",
  "Kobe Bufkin": "bufkiko01",
  "Reggie Bullock": "bullore01",
  "Trey Burke": "burketr01",
  "Alec Burks": "burksal01",
  "Deonte Burton": "burtode02",
  "Jared Butler": "butleja02",
  "Jimmy Butler": "butleji01",
  "John Butler": "butlejo01",
  "Matas Buzelis": "buzelma01",
  "Bruno Caboclo": "cabocbr01",
  "Devontae Cacok": "cacokde01",
  "Jamal Cain": "cainja01",
  "Kentavious Caldwell-Pope": "caldwke01",
  "Toumani Camara": "camarto01",
  "Facundo Campazzo": "campafa01",
  "Vlatko Čančar": "cancavl01",
  "Devin Cannady": "cannade01",
  "Clint Capela": "capelca01",
  "Vernon Carey Jr.": "careyve01",
  "Branden Carlson": "carlsbr01",
  "Bub Carrington": "carrica01",
  "Devin Carter": "cartede02",
  "Jevon Carter": "carteje01",
  "Wendell Carter Jr.": "cartewe01",
  "Michael Carter-Williams": "cartemi01",
  "D.J. Carton": "cartodj01",
  "Alex Caruso": "carusal01",
  "Stephon Castle": "castlst01",
  "Colin Castleton": "castlco01",
  "Willie Cauley-Stein": "caulewi01",
  "Ahmad Caver": "caverah01",
  "Malcolm Cazalon": "cazalma01",
  "Julian Champagnie": "champju02",
  "Justin Champagnie": "champju01",
  "Kennedy Chandler": "chandke01",
  "Zylan Cheatham": "cheatzy01",
  "Chris Chiozza": "chiozch01",
  "Ulrich Chomche": "chomcul01",
  "Marquese Chriss": "chrisma01",
  "Cam Christie": "chrisca02",
  "Max Christie": "chrisma02",
  "Josh Christopher": "chrisjo01",
  "Sidy Cissoko": "cissosi01",
  "Gary Clark": "clarkga01",
  "Jaylen Clark": "clarkja02",
  "Brandon Clarke": "clarkbr01",
  "Jordan Clarkson": "clarkjo01",
  "Nic Claxton": "claxtni01",
  "Chris Clemons": "clemoch01",
  "Donovan Clingan": "clingdo01",
  "Noah Clowney": "clownno01",
  "Amir Coffey": "coffeam01",
  "Isaiah Collier": "colliis01",
  "John Collins": "collijo01",
  "Yuri Collins": "colliyu01",
  "Zach Collins": "colliza01",
  "Chance Comanche": "comanch01",
  "Mike Conley": "conlemi01",
  "Pat Connaughton": "connapa01",
  "Tyler Cook": "cookty01",
  "Xavier Cooks": "cooksxa01",
  "Sharife Cooper": "coopesh01",
  "Bilal Coulibaly": "coulibi01",
  "Ricky Council IV": "councri01",
  "Robert Covington": "covinro01",
  "Allen Crabbe": "crabbal01",
  "Torrey Craig": "craigto01",
  "Isaiah Crawford": "crawfis01",
  "Jae Crowder": "crowdja01",
  "Jalen Crutcher": "crutcja01",
  "Cui Yongxi": "cuiyo01",
  "Jarrett Culver": "culveja01",
  "Cade Cunningham": "cunnica01",
  "Seth Curry": "curryse01",
  "Stephen Curry": "curryst01",
  "Tristan Da Silva": "dasiltr01",
  "Pacome Dadiet": "dadiepa01",
  "Dyson Daniels": "daniedy01",
  "N'Faly Dante": "nfalyda01",
  "Nate Darling": "darlina01",
  "Anthony Davis": "davisan02",
  "Johnny Davis": "davisjo06",
  "Terence Davis": "daviste02",
  "JD Davison": "davisjd01",
  "Darius Days": "daysda01",
  "DeMar DeRozan": "derozde01",
  "Dewayne Dedmon": "dedmode01",
  "Matthew Dellavedova": "dellama01",
  "Dexter Dennis": "dennide01",
  "RayJ Dennis": "dennira01",
  "Donte DiVincenzo": "divindo01",
  "Moussa Diabaté": "diabamo01",
  "Mamadi Diakite": "diakima01",
  "Cheick Diallo": "diallch01",
  "Hamidou Diallo": "diallha01",
  "Gradey Dick": "dickgr01",
  "Ousmane Dieng": "diengou01",
  "Rob Dillingham": "dilliro01",
  "Spencer Dinwiddie": "dinwisp01",
  "Luka Dončić": "doncilu01",
  "Tyler Dorsey": "dorsety01",
  "Luguentz Dort": "dortlu01",
  "Ayo Dosunmu": "dosunay01",
  "Devon Dotson": "dotsode01",
  "Sekou Doumbouya": "doumbse01",
  "Jeff Dowtin Jr.": "dowtije01",
  "PJ Dozier": "doziepj01",
  "Henri Drell": "drellhe01",
  "Andre Drummond": "drumman01",
  "Chris Duarte": "duartch01",
  "Alex Ducas": "ducasal01",
  "David Duke Jr.": "dukeda01",
  "Kris Dunn": "dunnkr01",
  "Ryan Dunn": "dunnry01",
  "Kevin Durant": "duranke01",
  "Jalen Duren": "durenja01",
  "Trevon Duval": "duvaltr01",
  "Tari Eason": "easonta01",
  "Jaime Echenique": "echenja01",
  "Zach Edey": "edeyza01",
  "Anthony Edwards": "edwaran01",
  "Carsen Edwards": "edwarca01",
  "Jesse Edwards": "edwarje01",
  "Justin Edwards": "edwarju01",
  "Kessler Edwards": "edwarke02",
  "Rob Edwards": "edwarro01",
  "Vince Edwards": "edwarvi01",
  "CJ Elleby": "ellebcj01",
  "Keon Ellis": "elliske01",
  "Joel Embiid": "embiijo01",
  "Tyson Etienne": "etienty01",
  "Drew Eubanks": "eubandr01",
  "Jacob Evans": "evansja02",
  "Tosan Evbuomwan": "evbuoto01",
  "Dante Exum": "exumda01",
  "Derrick Favors": "favorde01",
  "Bruno Fernando": "fernabr01",
  "Kyle Filipowski": "filipky01",
  "Dorian Finney-Smith": "finnedo01",
  "Malik Fitts": "fittsma01",
  "Adam Flagler": "flaglad01",
  "Trentyn Flowers": "flowetr01",
  "Malachi Flynn": "flynnma01",
  "Simone Fontecchio": "fontesi01",
  "Bryn Forbes": "forbebr01",
  "Aleem Ford": "fordal03",
  "Jordan Ford": "fordjo01",
  "Trent Forrest": "forretr01",
  "Michael Foster Jr.": "fostemi02",
  "Evan Fournier": "fournev01",
  "De'Aaron Fox": "foxde01",
  "Melvin Frazier": "frazime01",
  "Enrique Freeman": "freemen01",
  "Javon Freeman-Liberty": "freemja01",
  "Alex Fudge": "fudgeal01",
  "Markelle Fultz": "fultzma01",
  "Andrew Funk": "funkan01",
  "Johnny Furphy": "furphjo01",
  "Wenyen Gabriel": "gabriwe01",
  "Daniel Gafford": "gaffoda01",
  "Danilo Gallinari": "gallida01",
  "Langston Galloway": "gallola01",
  "Darius Garland": "garlada01",
  "Marcus Garrett": "garrema01",
  "Usman Garuba": "garubus01",
  "Luka Garza": "garzalu01",
  "Kaiser Gates": "gateska01",
  "Keyonte George": "georgke01",
  "Kyshawn George": "georgky01",
  "Paul George": "georgpa01",
  "Taj Gibson": "gibsota01",
  "Josh Giddey": "giddejo01",
  "Harry Giles": "gilesha01",
  "Shai Gilgeous-Alexander": "gilgesh01",
  "Anthony Gill": "gillan01",
  "Collin Gillespie": "gilleco01",
  "Jacob Gilyard": "gilyaja01",
  "Rudy Gobert": "goberru01",
  "Brandon Goodwin": "goodwbr01",
  "Jordan Goodwin": "goodwjo01",
  "Aaron Gordon": "gordoaa01",
  "Eric Gordon": "gordoer01",
  "Jazian Gortman": "gortmja01",
  "Devonte' Graham": "grahade01",
  "Treveon Graham": "grahatr01",
  "Jerami Grant": "grantje01",
  "Hassani Gravett": "graveha01",
  "RaiQuan Gray": "grayra01",
  "A.J. Green": "greenaj01",
  "Draymond Green": "greendr01",
  "Jalen Green": "greenja05",
  "JaMychal Green": "greenja01",
  "Javonte Green": "greenja02",
  "Jeff Green": "greenje02",
  "Josh Green": "greenjo02",
  "AJ Griffin": "griffaj01",
  "Quentin Grimes": "grimequ01",
  "Mouhamadou Gueye": "gueyemo01",
  "Mouhamed Gueye": "gueyemo02",
  "Kyle Guy": "guyky01",
  "Rui Hachimura": "hachiru01",
  "Ashton Hagans": "haganas01",
  "Tyrese Haliburton": "halibty01",
  "Devon Hall": "hallde01",
  "Jordan Hall": "halljo02",
  "Josh Hall": "halljo01",
  "PJ Hall": "hallpj01",
  "Tyler Hall": "hallty01",
  "R.J. Hampton": "hamptrj01",
  "Dusty Hannahs": "hannadu01",
  "Tim Hardaway Jr.": "hardati02",
  "James Harden": "hardeja01",
  "Jaden Hardy": "hardyja02",
  "Elijah Harkless": "harklej01",
  "Maurice Harkless": "harklma01",
  "Ron Harper Jr.": "harpero02",
  "Montrezl Harrell": "harremo01",
  "Gary Harris": "harriga01",
  "Jalen Harris": "harrija01",
  "Kevon Harris": "harrike01",
  "Tobias Harris": "harrito02",
  "Shaquille Harrison": "harrish01",
  "Josh Hart": "hartjo01",
  "Isaiah Hartenstein": "harteis01",
  "Sam Hauser": "hausesa01",
  "Jordan Hawkins": "hawkijo01",
  "Jaxson Hayes": "hayesja02",
  "Killian Hayes": "hayeski01",
  "Scoot Henderson": "hendesc01",
  "Taylor Hendricks": "hendrta01",
  "Dewan Hernandez": "hernade01",
  "Juancho Hernangómez": "hernaju01",
  "Willy Hernangómez": "hernawi01",
  "Tyler Herro": "herroty01",
  "Kevin Hervey": "herveke01",
  "Buddy Hield": "hieldbu01",
  "Haywood Highsmith": "highsha01",
  "George Hill": "hillge01",
  "Malcolm Hill": "hillma01",
  "Nate Hinton": "hintona01",
  "D'Moi Hodge": "hodgedm01",
  "Aaron Holiday": "holidaa01",
  "Jrue Holiday": "holidjr01",
  "Justin Holiday": "holidju01",
  "Ron Holland": "hollaro01",
  "Richaun Holmes": "holmeri01",
  "Chet Holmgren": "holmgch01",
  "Jalen Hood-Schifino": "hoodsja01",
  "Scotty Hopson": "hopsosc01",
  "Al Horford": "horfoal01",
  "Talen Horton-Tucker": "hortota01",
  "Danuel House Jr.": "houseda01",
  "Caleb Houstan": "houstca01",
  "Jett Howard": "howarje01",
  "Trevor Hudgins": "hudgitr01",
  "Kevin Huerter": "huertke01",
  "Jay Huff": "huffja01",
  "Elijah Hughes": "hugheel01",
  "Ariel Hukporti": "hukpoar01",
  "Feron Hunt": "huntfe01",
  "De'Andre Hunter": "huntede01",
  "R.J. Hunter": "hunterj01",
  "Matthew Hurt": "hurtma01",
  "Chandler Hutchison": "hutchch01",
  "Bones Hyland": "hylanbo01",
  "Oso Ighodaro": "ighodos01",
  "Joe Ingles": "inglejo01",
  "Brandon Ingram": "ingrabr01",
  "Harrison Ingram": "ingraha01",
  "Kyrie Irving": "irvinky01",
  "Jonathan Isaac": "isaacjo01",
  "Jaden Ivey": "iveyja01",
  "Wes Iwundu": "iwundwe01",
  "Andre Jackson Jr.": "jacksan01",
  "Frank Jackson": "jacksfr01",
  "GG Jackson II": "jacksgg01",
  "Isaiah Jackson": "jacksis01",
  "Jaren Jackson Jr.": "jacksja02",
  "Josh Jackson": "jacksjo02",
  "Justin Jackson": "jacksju01",
  "Quenton Jackson": "jacksqu01",
  "Reggie Jackson": "jacksre01",
  "Trayce Jackson-Davis": "jackstr02",
  "Bronny James": "jamesbr02",
  "Justin James": "jamesju01",
  "LeBron James": "jamesle01",
  "Jaime Jaquez Jr.": "jaqueja01",
  "DeJon Jarreau": "jarrede01",
  "DaQuan Jeffries": "jeffrda01",
  "Trey Jemison": "jemistr01",
  "Daniss Jenkins": "jenkida01",
  "John Jenkins": "jenkijo01",
  "Ty Jerome": "jeromty01",
  "Isaiah Joe": "joeis01",
  "AJ Johnson": "johnsaj01",
  "Alize Johnson": "johnsal02",
  "Cameron Johnson": "johnsca02",
  "David Johnson": "johnsda08",
  "Jalen Johnson": "johnsja05",
  "James Johnson": "johnsja01",
  "Keldon Johnson": "johnske04",
  "Keon Johnson": "johnske07",
  "Keshad Johnson": "johnske10",
  "Keyontae Johnson": "johnske08",
  "Stanley Johnson": "johnsst04",
  "Nikola Jokić": "jokicni01",
  "Carlik Jones": "jonesca03",
  "Colby Jones": "jonesco02",
  "Damian Jones": "jonesda03",
  "Derrick Jones Jr.": "jonesde02",
  "Dillon Jones": "jonesdi01",
  "Herbert Jones": "joneshe01",
  "Isaac Jones": "jonesis01",
  "Jemerrio Jones": "jonesje01",
  "Kai Jones": "joneska01",
  "Mason Jones": "jonesma05",
  "Spencer Jones": "jonessp01",
  "Tre Jones": "jonestr01",
  "Tyus Jones": "jonesty01",
  "DeAndre Jordan": "jordade01",
  "Cory Joseph": "josepco01",
  "Nikola Jović": "jovicni01",
  "Johnny Juzang": "juzanjo01",
  "Mfiondu Kabengele": "kabenmf01",
  "Frank Kaminsky": "kaminfr01",
  "Yuki Kawamura": "kawamyu01",
  "Trevor Keels": "keelstr01",
  "Kylor Kelley": "kelleky01",
  "Luke Kennard": "kennalu01",
  "Walker Kessler": "kesslwa01",
  "Braxton Key": "keybr01",
  "George King": "kingge03",
  "Louis King": "kinglo02",
  "Corey Kispert": "kispeco01",
  "Maxi Kleber": "klebima01",
  "Bobi Klintman": "klintbo01",
  "Dalton Knecht": "knechda01",
  "Nathan Knight": "knighna01",
  "Kevin Knox": "knoxke01",
  "Tyler Kolek": "kolekty01",
  "Christian Koloko": "kolokch01",
  "John Konchar": "konchjo01",
  "Furkan Korkmaz": "korkmfu01",
  "Luke Kornet": "kornelu01",
  "Vit Krejci": "krejcvi01",
  "Jonathan Kuminga": "kuminjo01",
  "Kyle Kuzma": "kuzmaky01",
  "Jake LaRavia": "laravja01",
  "Zach LaVine": "lavinza01",
  "Anthony Lamb": "lamban01",
  "Jock Landale": "landajo01",
  "Romeo Langford": "langfro01",
  "Pelle Larsson": "larsspe01",
  "A.J. Lawson": "lawsoaj01",
  "Jake Layman": "laymaja01",
  "Caris LeVert": "leverca01",
  "Jalen Lecque": "lecquja01",
  "Damion Lee": "leeda03",
  "Saben Lee": "leesa01",
  "Alex Len": "lenal01",
  "Kawhi Leonard": "leonaka01",
  "Meyers Leonard": "leoname01",
  "Malevy Leons": "leonsma01",
  "Kira Lewis Jr.": "lewiski01",
  "Maxwell Lewis": "lewisma05",
  "E.J. Liddell": "liddeej01",
  "Damian Lillard": "lillada01",
  "Nassir Little": "littlna01",
  "Dereck Lively II": "livelde01",
  "Isaiah Livers": "liveris01",
  "Chris Livingston": "livinch01",
  "Kenneth Lofton Jr.": "loftoke01",
  "Kevon Looney": "looneke01",
  "Brook Lopez": "lopezbr01",
  "Didi Louzada": "louzama01",
  "Kevin Love": "loveke01",
  "Kyle Lowry": "lowryky01",
  "Seth Lundy": "lundyse01",
  "Timothé Luwawu-Cabarrot": "luwawti01",
  "Trey Lyles": "lylestr01",
  "Théo Maledon": "maledth01",
  "Sandro Mamukelashvili": "mamuksa01",
  "Karim Mané": "maneka01",
  "Terance Mann": "mannte01",
  "Tre Mann": "manntr01",
  "Nico Mannion": "mannini01",
  "Boban Marjanović": "marjabo01",
  "Lauri Markkanen": "markkla01",
  "Naji Marshall": "marshna01",
  "Caleb Martin": "martica02",
  "Cody Martin": "martico01",
  "Jaylen Martin": "martija02",
  "Kelan Martin": "martike03",
  "KJ Martin": "martike04",
  "Tyrese Martin": "martity01",
  "Garrison Mathews": "mathega01",
  "Dakota Mathias": "mathida01",
  "Bennedict Mathurin": "mathube01",
  "Karlo Matković": "matkoka01",
  "Wesley Matthews": "matthwe02",
  "Tyrese Maxey": "maxeyty01",
  "Skylar Mays": "mayssk01",
  "Miles McBride": "mcbrimi01",
  "Jared McCain": "mccaija01",
  "Patrick McCaw": "mccawpa01",
  "Mac McClung": "mccluma01",
  "CJ McCollum": "mccolcj01",
  "T.J. McConnell": "mccontj01",
  "Kevin McCullar Jr.": "mcculke01",
  "Jaden McDaniels": "mcdanja02",
  "Jalen McDaniels": "mcdanja01",
  "Doug McDermott": "mcderdo01",
  "Sean McDermott": "mcderse01",
  "JaVale McGee": "mcgeeja01",
  "Bryce McGowens": "mcgowbr01",
  "Rodney McGruder": "mcgruro01",
  "Alfonzo McKinnie": "mckinal01",
  "JaQuori McLaughlin": "mclauja01",
  "Jordan McLaughlin": "mclaujo01",
  "Jack McVeigh": "mcveija01",
  "De'Anthony Melton": "meltode01",
  "Nathan Mensah": "mensana01",
  "Sam Merrill": "merrisa01",
  "Chimezie Metu": "metuch01",
  "Vasilije Micić": "micicva01",
  "Khris Middleton": "middlkh01",
  "Eric Mika": "mikaer01",
  "Brandon Miller": "millebr02",
  "Emanuel Miller": "milleem01",
  "Jordan Miller": "millejo02",
  "Leonard Miller": "millele01",
  "Malcolm Miller": "millema01",
  "Dariq Whitehead": "whiteda01",
  "Patty Mills": "millspa02",
  "Shake Milton": "miltosh01",
  "Justin Minaya": "minayju01",
  "Riley Minix": "minixri01",
  "Josh Minott": "minotjo01",
  "Yves Missi": "missiyv01",
  "Ajay Mitchell": "mitchaj01",
  "Davion Mitchell": "mitchda01",
  "Donovan Mitchell": "mitchdo01",
  "Evan Mobley": "mobleev01",
  "Isaiah Mobley": "mobleis01",
  "Jonathan Mogbo": "mogbojo01",
  "Adam Mokoka": "mokokad01",
  "Chima Moneke": "monekch01",
  "Malik Monk": "monkma01",
  "Moses Moody": "moodymo01",
  "Xavier Moon": "moonxa01",
  "Taze Moore": "mooreta02",
  "Wendell Moore Jr.": "moorewe01",
  "Ja Morant": "moranja01",
  "Juwan Morgan": "morgaju01",
  "Marcus Morris": "morrima03",
  "Markieff Morris": "morrima02",
  "Monte Morris": "morrimo01",
  "Emmanuel Mudiay": "mudiaem01",
  "Mychal Mulder": "muldemy01",
  "Trey Murphy III": "murphtr02",
  "Dejounte Murray": "murrade01",
  "Jamal Murray": "murraja01",
  "Keegan Murray": "murrake02",
  "Kris Murray": "murrakr01",
  "Mike Muscala": "muscami01",
  "Svi Mykhailiuk": "mykhasv01",
  "Larry Nance Jr.": "nancela02",
  "Pete Nance": "nancepe01",
  "Shabazz Napier": "napiesh01",
  "Andrew Nembhard": "nembhan01",
  "RJ Nembhard Jr.": "nembhrj01",
  "Aaron Nesmith": "nesmiaa01",
  "Raul Neto": "netora01",
  "Tristen Newton": "newtotr01",
  "Georges Niang": "niangge01",
  "Daishen Nix": "nixda01",
  "Zeke Nnaji": "nnajize01",
  "Nerlens Noel": "noelne01",
  "Miles Norris": "norrimi01",
  "Jaylen Nowell": "nowelja01",
  "Markquis Nowell": "nowelma01",
  "Frank Ntilikina": "ntilila01",
  "Kendrick Nunn": "nunnke01",
  "Jusuf Nurkić": "nurkiju01",
  "David Nwaba": "nwabada01",
  "Jordan Nwora": "nworajo01",
  "Royce O'Neale": "onealro01",
  "Jahlil Okafor": "okafoja01",
  "Chuma Okeke": "okekech01",
  "Josh Okogie": "okogijo01",
  "Onyeka Okongwu": "okongon01",
  "Isaac Okoro": "okorois01",
  "KZ Okpala": "okpalkz01",
  "Victor Oladipo": "oladivi01",
  "Quincy Olivari": "olivaqu01",
  "Cameron Oliver": "oliveca01",
  "Kelly Olynyk": "olynyke01",
  "Eugene Omoruyi": "omorueu01",
  "Miye Oni": "onimi01",
  "Cedi Osman": "osmande01",
  "Daniel Oturu": "oturuda01",
  "Kelly Oubre Jr.": "oubreke01",
  "Trayvon Palmer": "palmetr01",
  "Jeremy Pargo": "pargoje01",
  "Eric Paschall": "pascher01",
  "Chris Paul": "paulch01",
  "Cameron Payne": "payneca01",
  "Elfrid Payton": "paytoel01",
  "Gary Payton II": "paytoga02",
  "Norvel Pelle": "pelleno01",
  "Mãozinha Pereira": "pereima01",
  "Reggie Perry": "perryre01",
  "Drew Peterson": "peterdr01",
  "Filip Petrušev": "petrufi01",
  "Julian Phillips": "phillju01",
  "Jalen Pickett": "pickeja02",
  "Jamorko Pickett": "pickeja01",
  "Theo Pinson": "pinsoth01",
  "Scotty Pippen Jr.": "pippesc02",
  "Daeqwon Plowden": "plowdda01",
  "Mason Plumlee": "plumlma01",
  "Brandin Podziemski": "podzibr01",
  "Jakob Poeltl": "poeltja01",
  "Aleksej Pokusevski": "pokusal01",
  "Shamorie Ponds": "pondssh01",
  "Yves Pons": "ponsyv01",
  "Jordan Poole": "poolejo01",
  "Craig Porter Jr.": "portecr01",
  "Jontay Porter": "portejo01",
  "Kevin Porter Jr.": "porteke02",
  "Michael Porter Jr.": "portemi01",
  "Bobby Portis": "portibo01",
  "Kristaps Porziņģis": "porzikr01",
  "Quinten Post": "postqu01",
  "Micah Potter": "pottemi01",
  "Dwight Powell": "poweldw01",
  "Norman Powell": "powelno01",
  "Jason Preston": "prestja01",
  "Joshua Primo": "primojo01",
  "Taurean Prince": "princta02",
  "Payton Pritchard": "pritcpa01",
  "Olivier-Maxence Prosper": "prospol01",
  "Zyon Pullin": "pullizy01",
  "Trevelin Queen": "queentr01",
  "Neemias Queta": "quetane01",
  "Immanuel Quickley": "quickim01",
  "Lester Quiñones": "quinole01",
  "Jahmi'us Ramsey": "ramseja01",
  "Chasson Randle": "randlch01",
  "Julius Randle": "randlju01",
  "Duop Reath": "reathdu01",
  "Austin Reaves": "reaveau01",
  "Josh Reaves": "reavejo02",
  "Cam Reddish": "reddica01",
  "Davon Reed": "reedda01",
  "Paul Reed": "reedpa01",
  "Alex Reese": "reeseal01",
  "Antonio Reeves": "reevean01",
  "Naz Reid": "reidna01",
  "Jared Rhoden": "rhodeja01",
  "Nick Richards": "richani01",
  "Josh Richardson": "richajo01",
  "Grant Riller": "rillegr01",
  "Zaccharie Risacher": "risacza01",
  "Austin Rivers": "riverau01",
  "Liam Robbins": "robbili01",
  "Duncan Robinson": "robindu01",
  "Jerome Robinson": "robinje01",
  "Justin Robinson": "robinju01",
  "Mitchell Robinson": "robinmi01",
  "Orlando Robinson": "robinor01",
  "Jeremiah Robinson-Earl": "robinje02",
  "Isaiah Roby": "robyis01",
  "David Roddy": "roddyda01",
  "Ryan Rollins": "rolliry01",
  "Jackson Rowe": "roweja01",
  "Terry Rozier": "roziete01",
  "Rayan Rupert": "ruperra01",
  "D'Angelo Russell": "russeda01",
  "Matt Ryan": "ryanma01",
  "Domantas Sabonis": "sabondo01",
  "Tidjane Salaün": "salauti01",
  "Luka Šamanić": "samanlu01",
  "Brandon Sampson": "sampsbr01",
  "Jermaine Samuels": "samueje01",
  "Adama Sanogo": "sanogad01",
  "Gui Santos": "santogu01",
  "Dario Šarić": "saricda01",
  "Alex Sarr": "sarral01",
  "Olivier Sarr": "sarrol01",
  "Marcus Sasser": "sassema01",
  "Jordan Schakel": "schakjo01",
  "Baylor Scheierman": "scheiba01",
  "Admiral Schofield": "schofad01",
  "Dennis Schröder": "schrode01",
  "Jay Scrubb": "scrubja01",
  "Dereon Seabron": "seabrde01",
  "Alperen Şengün": "sengual01",
  "Brice Sensabaugh": "sensabr01",
  "Collin Sexton": "sextoco01",
  "Landry Shamet": "shamela01",
  "Terrence Shannon Jr.": "shannte01",
  "Day'Ron Sharpe": "sharpda01",
  "Shaedon Sharpe": "sharpsh01",
  "Marial Shayok": "shayoma01",
  "Jamal Shead": "sheadja01",
  "Ben Sheppard": "sheppbe01",
  "Reed Sheppard": "sheppre01",
  "Pascal Siakam": "siakapa01",
  "Chris Silva": "silvach01",
  "Ben Simmons": "simmobe01",
  "Kobi Simmons": "simmoko01",
  "Marko Simonovic": "simonma01",
  "Anfernee Simons": "simonan01",
  "KJ Simpson": "simpskj01",
  "Zavier Simpson": "simpsza01",
  "Jaylen Sims": "simsja01",
  "Jericho Sims": "simsje01",
  "Deividas Sirvydis": "sirvyde01",
  "Dmytro Skapintsev": "skapidm01",
  "Jalen Slawson": "slawsja01",
  "Alen Smailagić": "smailal01",
  "Javonte Smart": "smartja01",
  "Marcus Smart": "smartma01",
  "Dennis Smith Jr.": "smithde03",
  "Dru Smith": "smithdr01",
  "Ish Smith": "smithis01",
  "Jabari Smith Jr.": "smithja05",
  "Jalen Smith": "smithja04",
  "Nick Smith Jr.": "smithni01",
  "Terquavion Smith": "smithte01",
  "Tolu Smith": "smithto05",
  "Tyler Smith": "smithty02",
  "Zhaire Smith": "smithzh01",
  "Xavier Sneed": "sneedxa01",
  "Jeremy Sochan": "sochaje01",
  "Ray Spalding": "spaldra01",
  "Omari Spellman": "spellom01",
  "Cam Spencer": "spencca01",
  "Pat Spencer": "spencpa01",
  "Jaden Springer": "sprinja01",
  "Cassius Stanley": "stanlca01",
  "Nik Stauskas": "stausni01",
  "Isaiah Stevens": "steveis01",
  "Lamar Stevens": "stevela01",
  "Isaiah Stewart": "stewais01",
  "Julian Strawther": "strawju01",
  "Max Strus": "strusma01",
  "Jalen Suggs": "suggsja01",
  "Edmond Sumner": "sumneed01",
  "Cole Swider": "swideco01",
  "Craig Sword": "swordcr01",
  "Keifer Sykes": "sykeske01",
  "Jae'Sean Tate": "tateja01",
  "Jayson Tatum": "tatumja01",
  "Terry Taylor": "taylote01",
  "Garrett Temple": "templga01",
  "Dalen Terry": "terryda01",
  "Tyrell Terry": "terryty01",
  "Daniel Theis": "theisda01",
  "Brodric Thomas": "thomabr01",
  "Cam Thomas": "thomaca02",
  "Isaiah Thomas": "thomais02",
  "Khyri Thomas": "thomakh01",
  "Amen Thompson": "thompam01",
  "Ausar Thompson": "thompau01",
  "Klay Thompson": "thompkl01",
  "Tristan Thompson": "thomptr01",
  "JT Thor": "thorjt01",
  "Matisse Thybulle": "thybuma01",
  "Killian Tillie": "tilliki02",
  "Xavier Tillman Sr.": "tillmxa01",
  "Drew Timme": "timmedr01",
  "Isaiah Todd": "toddis01",
  "Nae'Qwan Tomlin": "tomlina01",
  "Jacob Toppin": "toppija01",
  "Obi Toppin": "toppiob01",
  "Juan Toscano-Anderson": "toscaju01",
  "Karl-Anthony Towns": "townska01",
  "Armel Traoré": "armeltr01",
  "Luke Travers": "travelu01",
  "Gary Trent Jr.": "trentga02",
  "Oscar Tshiebwe": "tshieos01",
  "P.J. Tucker": "tuckepj01",
  "Rayjon Tucker": "tuckera01",
  "Myles Turner": "turnemy01",
  "Hunter Tyson": "tysonhu01",
  "Jaylon Tyson": "tysonja01",
  "Stanley Umude": "umudest01",
  "Jonas Valančiūnas": "valanjo01",
  "Denzel Valentine": "valende01",
  "Fred VanVleet": "vanvlfr01",
  "Jarred Vanderbilt": "vandeja01",
  "Devin Vassell": "vassede01",
  "Sasha Vezenkov": "vezenal01",
  "Gabe Vincent": "vincega01",
  "Noah Vonleh": "vonleno01",
  "Nikola Vučević": "vucevni01",
  "Tristan Vukcevic": "vukcetr01",
  "Dean Wade": "wadede01",
  "Franz Wagner": "wagnefr01",
  "Moritz Wagner": "wagnemo01",
  "Ish Wainright": "wainris01",
  "Jabari Walker": "walkeja01",
  "Jarace Walker": "walkeja02",
  "Lonnie Walker IV": "walkelo01",
  "M.J. Walker": "walkemj01",
  "John Wall": "walljo01",
  "Cason Wallace": "wallaca01",
  "Keaton Wallace": "wallake01",
  "Jordan Walsh": "walshjo01",
  "Ja'Kobe Walter": "walteja01",
  "Kel'el Ware": "wareke01",
  "T.J. Warren": "warretj01",
  "Duane Washington Jr.": "washidu02",
  "P.J. Washington": "washipj01",
  "TyTy Washington Jr.": "washity02",
  "Yuta Watanabe": "watanyu01",
  "Lindy Waters III": "waterli01",
  "Tremont Waters": "watertr01",
  "Trendon Watford": "watfotr01",
  "Anton Watson": "watsoan02",
  "Peyton Watson": "watsope01",
  "Quinndary Weatherspoon": "weathqu01",
  "Jaylen Wells": "wellsja01",
  "Thomas Welsh": "welshth01",
  "Victor Wembanyama": "wembavi01",
  "Blake Wesley": "weslebl01",
  "Russell Westbrook": "westbru01",
  "Phillip Wheeler": "wheelph02",
  "Coby White": "whiteco01",
  "Derrick White": "whitede01",
  "Jack White": "whiteja03",
  "Okaro White": "whiteok01",
  "Cam Whitmore": "whitmca01",
  "Joe Wieskamp": "wieskjo01",
  "Aaron Wiggins": "wiggiaa01",
  "Andrew Wiggins": "wiggian01",
  "Lindell Wigginton": "wiggili01",
  "Alondes Williams": "willial06",
  "Brandon Williams": "willibr03",
  "Cody Williams": "willico04",
  "Donovan Williams": "willido02",
  "Grant Williams": "willigr01",
  "Jalen Williams": "willija06",
  "Jaylin Williams": "willija07",
  "Jeenathan Williams": "willije02",
  "Kenrich Williams": "willike04",
  "Malik Williams": "willima11",
  "Mark Williams": "willima07",
  "Patrick Williams": "willipa01",
  "Robert Williams": "williro04",
  "Vince Williams Jr.": "willivi01",
  "Ziaire Williams": "willizi02",
  "Zion Williamson": "willizi01",
  "D.J. Wilson": "wilsodj01",
  "Jalen Wilson": "wilsoja03",
  "Dylan Windler": "windldy01",
  "Justise Winslow": "winslju01",
  "Cassius Winston": "winstca01",
  "James Wiseman": "wisemja01",
  "Isaiah Wong": "wongis01",
  "Christian Wood": "woodch01",
  "Robert Woodard II": "woodaro01",
  "Delon Wright": "wrighde01",
  "McKinley Wright IV": "wrighmc01",
  "Justin Wright-Foreman": "wrighju02",
  "Guerschon Yabusele": "yabusgu01",
  "Gabe York": "yorkga01",
  "Jahmir Young": "youngja05",
  "Thaddeus Young": "youngth01",
  "Trae Young": "youngtr01",
  "Omer Yurtseven": "yurtsom01",
  "Cody Zeller": "zelleco01",
  "Ivica Zubac": "zubaciv01"
}
wnba_players = {
    "Breanna Stewart": "stewabr01w",
    "A'ja Wilson": "wilsoa01w",
    "Sabrina Ionescu": "ionessa01w",
    "Napheesa Collier": "collina01w",
    "Kelsey Plum": "plumke01w",
    "Jewell Loyd": "loydje01w",
    "Arike Ogunbowale": "ogunbar01w",
    "Brittney Griner": "grinebr01w",
    "Elena Delle Donne": "delleel01w",
    "Courtney Vandersloot": "vandeco01w",
    "Candace Parker": "parkeca01w",
    "Skylar Diggins‑Smith": "diggisk01w",
    "Chelsea Gray": "graych01w",
    "Jonquel Jones": "jonesjo01w",
    "Natasha Howard": "howarna01w",
    "Kayla McBride": "mcbrika01w",
    "Satou Sabally": "sabalsa01w",
    "Alyssa Thomas": "thomaal01w",
    "Allisha Gray": "grayal01w",
    "Courtney Williams": "willico01w",
    "Kelsey Mitchell": "mitchele01w",
    "Aari McDonald": "mcdonaa01w",
    "Tianna Hawkins": "hawkiti01w",
    "Michaela Onyenwere": "onyenm01w",
    "Myisha Hines‑Allen": "hinesmy01w",
    "Erica Wheeler": "wheeler01w",
    "Rachel Banham": "banhara01w",
    "Natalie Achonwa": "achonna01w",
    "Liz Cambage": "cambali01w",
    "Chelsea Buckley": "bucklch01w",
    "Betnijah Laney": "laneybe01w",
    "Mercedes Russell": "russeme01w",
    "Tyasha Harris": "harrity01w",
    "Dana Evans": "evansda01w",
    "Amanda Zahui B.": "zahuiba01w",
    "Lexie Brown": "brownle01w",
    "Angel Reese": "reesear01w",
    "Paige Bueckers": "bueckpa01w",
    "Courtney Williams": "willico01w",
    "Gabby Williams": "williga01w",
    "Jackie Young": "youngja01w",
    "Sonia Citron": "citroso01w",
    "Kiki Iriafen": "iriafki01w",
    "Kayla Thornton": "thornka01w",
    # ... continuă lista până la 200
}

# 🌐 Interfață Streamlit
st.set_page_config(page_title=" NBA/WNBA Predictions ", layout="centered")
st.title("🏀 NBA/WNBA Predictions")
#league = st.radio("Alege liga:", ["NBA", "WNBA"])
league = st.selectbox("Select league:", ["NBA", "WNBA"]).lower()
players = nba_players if league == "nba" else wnba_players
player_name = st.selectbox("Select player:", list(players.keys()))
debug = st.checkbox("🔎 Debug mode")

if player_name:
    pid = players[player_name]
    df_all = pd.concat([
        scrape_stats(generate_url(pid, league, y), league, debug)
        for y in [2024, 2025]
    ], ignore_index=True)

    if df_all.empty:
        st.error("⚠️ No valid data found.")
    else:
        st.subheader("📊 Recent statistics")
        st.dataframe(df_all.tail(5), use_container_width=True)

        preds, rmses = predict_next_game(df_all)

        st.subheader("🔮 Predict next match")
        st.table(pd.DataFrame([preds]))

        st.subheader("📉 RMSE (eroare model pe date istorice)")
        st.table(pd.DataFrame([rmses]))
